### ISSUE TITLE
Unique Phone, low priority(We can argue that userstory mean unique username only)

### ISSUE THREAD

**Issue by youwei1-sudo** [CMPUT301W20T16/QuicaR#36]
If we treat that user story 
All contact information also unique and can be updated later on 
I may need some help from Database
Hard for me, to check without help from database

**Comment by Jeremy0818** [comment]
I have updated UserDataHelper class for checking unique username, email and phone number as well at the same time by calling just one static method called checkUserExists(username, email, phone, listener).

**Comment by youwei1-sudo** [comment]
Cool love u
